feat: call build specific runtime functions
go-vela/pkg-executor pull request #179
Opened 2021-10-09 03:35 UTC by cognifloyd

In kubernetes native secrets and a variety of `VELA_` variables do not get populated in the pod environment.

This was happening because container environment is immutable after pod creation. So, we need to run `Runtime.SetupContainer` for all containers before we create the pod in kubernetes. Then, we have to move `container.Env` initialization to just before pod creation, so that all of the vars that get populated *AFTER* `SetupContainer` make it to the container.

So, I added 4 methods to the `Runtime` engine interface:
- `SetupBuild`
- `AssembleBuild`
- `RemoveBuild`
- `InspectBuild`

This allows us to manage the pod at the build level instead of using heuristics to try and manage creating/removing the pod in the container management functions.

Requires:
- https://github.com/go-vela/pkg-runtime/pull/148

2021-10-13 04:17 UTC, cognifloyd commented
Please see https://github.com/go-vela/pkg-runtime/pull/148#issuecomment-941816412 for more details on the `VELA_*` vars that were not getting populated. With both of these PRs, this issue is fixed.

2021-10-25 17:27 UTC, cognifloyd commented on executor/linux/build.go
> +	}
I'm not sure if we need this here since we're doing this in a `defer func()` above.

2021-10-25 17:27 UTC, cognifloyd commented on executor/local/build.go
> +	}
I'm not sure if we need this here since we're doing this in a `defer func()` above.

2021-10-25 17:28 UTC, cognifloyd commented
https://github.com/go-vela/pkg-runtime/pull/148 was merged, so this is ready for review.

2021-10-25 18:33 UTC, jbrockopp requested changes

2021-10-25 18:33 UTC, jbrockopp commented on executor/linux/build.go
> +		return fmt.Errorf("unable to create build %s: %w", c.pipeline.ID, c.err)
Do you think this log message should reflect the function name?

```suggestion
		return fmt.Errorf("unable to setup build %s: %w", c.pipeline.ID, c.err)
```

2021-10-25 18:33 UTC, jbrockopp commented on executor/linux/build.go
> +	}
I think we can remove this since we are already calling this in the `defer func()` 👍

2021-10-25 18:33 UTC, jbrockopp commented on executor/linux/step.go
> +	_step.SetStatus(constants.StatusPending)
I wonder if we could replace this with `go-vela/types/library.StepFromContainer()`?

https://pkg.go.dev/github.com/go-vela/types/library#StepFromContainer

2021-10-25 18:33 UTC, jbrockopp commented on executor/linux/step.go
> +}
I wonder if we could replace this with `go-vela/types/library.StepFromContainer()`?

https://pkg.go.dev/github.com/go-vela/types/library#StepFromContainer

2021-10-25 18:33 UTC, jbrockopp commented on executor/linux/step.go
> +	}
I wonder if we could replace this with `go-vela/types/library.StepFromContainer()`?

https://pkg.go.dev/github.com/go-vela/types/library#StepFromContainer

2021-10-25 18:33 UTC, jbrockopp commented on executor/local/build.go
> +	}
I think we can remove this since we are already calling this in the `defer func()` 👍

2021-10-25 18:33 UTC, jbrockopp commented on executor/local/step.go
> +	_step.SetStatus(constants.StatusPending)
I wonder if we could replace this with `go-vela/types/library.StepFromContainer()`?

https://pkg.go.dev/github.com/go-vela/types/library#StepFromContainer

2021-10-25 18:33 UTC, jbrockopp commented on executor/local/step.go
> +	}
I wonder if we could replace this with `go-vela/types/library.StepFromContainer()`?

https://pkg.go.dev/github.com/go-vela/types/library#StepFromContainer

2021-10-25 18:36 UTC, cognifloyd commented on executor/linux/build.go
> +		return fmt.Errorf("unable to create build %s: %w", c.pipeline.ID, c.err)
works for me. I was copying some of the other functions which are also inconsistent.

2021-10-25 18:55 UTC, cognifloyd commented on executor/linux/step.go
> +}
No.
I think `library.StepFromContainer()` would be more appropriately named, `library.StepFromContainerEnvironment()` because it uses `ctn.Environment` to generate the `library.Step`.

We can't use `library.StepFromContainer`Environment because `ctn.Environment` is not populated until after we call this in `PlanStep`.

We could probably move `newLibraryStep` into another func with this signature in `go-vela/types/library/step.go`, but we'd need to figure out what to do about the naming.
```go
StepFromContainer(build *Build, ctn *pipeline.Container) *Step
```

Note that we'd need to pass in `c.build` and not just the container, so maybe `StepFromContainerAndBuild`? or we rename the current function?

2021-10-25 18:56 UTC, cognifloyd commented on executor/linux/step.go
> +}
https://github.com/go-vela/types/blob/5ce19678cfa70be6751d527b8bb4b86986babf70/library/step.go#L512

2021-10-25 19:02 UTC, cognifloyd commented on executor/linux/step.go
> +}
We might be able to do this:
```go
func (b *Build) StepFromContainer(ctn *pipeline.Container) *Step {...}
```
And then we'd call `c.build.StepFromContainer(ctn)`, though that feels a little weird.

2021-10-25 19:26 UTC, jbrockopp commented on executor/linux/step.go
> +}
@cognifloyd what if we augmented `library.StepFromContainer()` to use the environment variables as fall back values? And instead, have it adopt the actual field values from the `pipeline.Container` object as the primary?

2021-10-25 19:30 UTC, jbrockopp commented on executor/linux/step.go
> +}
Nevermind.. I don't think that will work since the `pipeline.Container` object doesn't have all that information.

2021-10-25 19:47 UTC, jbrockopp requested changes
Looks like the `validate` workflow is still failing:

https://github.com/go-vela/pkg-executor/runs/4001465504?check_suite_focus=true

If you can't see that link, I believe the issue is with the deps in the `go.sum` file.

To resolve this, you can run a `make clean` 👍

2021-10-25 20:11 UTC, cognifloyd commented on executor/linux/step.go
> +}
We could do something like this with StepFromContainer:
https://github.com/go-vela/types/compare/master...cognifloyd:stepFromContainer

afaict pkg-executor is the only user of `StepFromContainer` (in `DestroyContainer`), so we can very simply switch that over to use `StepFromContainerEnvironment`.

2021-10-25 20:17 UTC, jbrockopp commented on executor/linux/step.go
> +}
I think what you have now is fine to progress forward with 👍 

But I think what you're showing with the types change would be a nice addition to make in the future too.

2021-10-25 20:19 UTC, jbrockopp requested changes

2021-10-25 20:19 UTC, jbrockopp commented on executor/linux/step.go
> +func (c *client) newLibraryStep(ctx context.Context, ctn *pipeline.Container) (*library.Step, error) {
Doesn't look like we use the `ctx` variable with a type of `Context.Context` in this function.

Can this be removed?

2021-10-25 20:19 UTC, jbrockopp commented on executor/local/step.go
> +func (c *client) newLibraryStep(ctx context.Context, ctn *pipeline.Container) (*library.Step, error) {
Doesn't look like we use the `ctx` variable with a type of `Context.Context` in this function.

Can this be removed?

2021-10-25 20:59 UTC, cognifloyd commented on executor/linux/step.go
> +func (c *client) newLibraryStep(ctx context.Context, ctn *pipeline.Container) (*library.Step, error) {
Done. I was copying the general interface of the other client methods. But that doesn't matter, so I dropped it.

2021-10-25 21:00 UTC, jbrockopp submitted a review, later dismissed
LGTM

2021-10-25 21:04 UTC, jbrockopp approved these changes
LGTM

2021-10-25 22:25 UTC, cognifloyd commented on executor/linux/step.go
> +}
K. I think I found a clean way to move this to `library.Step`. See https://github.com/go-vela/types/pull/205

2021-10-26 15:00 UTC, KellyMerrick approved these changes
lgtm

2021-10-26 15:00 UTC, merged